/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDemoRouteImport } from './routes/_authenticated/demo'
import { Route as AuthenticatedDoctorRouteImport } from './routes/_authenticated/doctor'
import { Route as AuthenticatedIntakeRouteImport } from './routes/_authenticated/intake'
import { Route as AuthenticatedTriageRouteImport } from './routes/_authenticated/triage'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_authenticated/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDemoRoute = AuthenticatedDemoRouteImport.update({
  id: '/_authenticated/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDoctorRoute = AuthenticatedDoctorRouteImport.update({
  id: '/_authenticated/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIntakeRoute = AuthenticatedIntakeRouteImport.update({
  id: '/_authenticated/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTriageRoute = AuthenticatedTriageRouteImport.update({
  id: '/_authenticated/triage',
  path: '/triage',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AuthenticatedAdminRoute
  '/demo': typeof AuthenticatedDemoRoute
  '/doctor': typeof AuthenticatedDoctorRoute
  '/intake': typeof AuthenticatedIntakeRoute
  '/triage': typeof AuthenticatedTriageRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AuthenticatedAdminRoute
  '/demo': typeof AuthenticatedDemoRoute
  '/doctor': typeof AuthenticatedDoctorRoute
  '/intake': typeof AuthenticatedIntakeRoute
  '/triage': typeof AuthenticatedTriageRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/demo': typeof AuthenticatedDemoRoute
  '/_authenticated/doctor': typeof AuthenticatedDoctorRoute
  '/_authenticated/intake': typeof AuthenticatedIntakeRoute
  '/_authenticated/triage': typeof AuthenticatedTriageRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/admin' | '/demo' | '/doctor' | '/intake' | '/triage' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/admin' | '/demo' | '/doctor' | '/intake' | '/triage' | '/'
  id:
    | '__root__'
    | '/_authenticated/admin'
    | '/_authenticated/demo'
    | '/_authenticated/doctor'
    | '/_authenticated/intake'
    | '/_authenticated/triage'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDemoRoute: typeof AuthenticatedDemoRoute
  AuthenticatedDoctorRoute: typeof AuthenticatedDoctorRoute
  AuthenticatedIntakeRoute: typeof AuthenticatedIntakeRoute
  AuthenticatedTriageRoute: typeof AuthenticatedTriageRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/demo': {
      id: '/_authenticated/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof AuthenticatedDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/doctor': {
      id: '/_authenticated/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof AuthenticatedDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/intake': {
      id: '/_authenticated/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof AuthenticatedIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/triage': {
      id: '/_authenticated/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof AuthenticatedTriageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDemoRoute: AuthenticatedDemoRoute,
  AuthenticatedDoctorRoute: AuthenticatedDoctorRoute,
  AuthenticatedIntakeRoute: AuthenticatedIntakeRoute,
  AuthenticatedTriageRoute: AuthenticatedTriageRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
